apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::<ACCOUNT_ID>:role/UdacityFlaskDeployCBKubectlRole
      username: build 
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::509405362937:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-M9OIY1OKPOFM
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-29T11:20:33Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1498"
  uid: 3283f882-06a9-4cb0-80ad-5d1b61eab126
