apiVersion: v1
data:
  mapRoles: |
   - groups:
     - system:masters
     rolearn: arn:aws:iam::509405362937:role/UdacityFlaskDeployCBKubectlRole
     username: build  
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::509405362937:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-3TFE8YUSYQ8L
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-25T15:24:09Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1750"
  uid: abbeb169-862e-4001-88ec-68eac19e453a
