apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::509405362937:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1HQ36SJ9NXV0B
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::509405362937:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-29T10:07:18Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1597"
  uid: 8cfe3b15-ff7c-49b7-895e-a6214f9c05b4
